server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Rollin10!
#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers
logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework : INFO
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE